window.customResources = [
  {
    competency: "Digital Information Literacy",
    level: "knowledge",
    title: "Evaluating Sources",
    description: "Harvard University's guide on assessing the reliability and accuracy of various information sources.",
    URL: "https://usingsources.fas.harvard.edu/evaluating-sources-0",
    rating: 1,
  },
  {
    competency: "Digital Information Literacy",
    level: "knowledge",
    title: "How to Know if a Source Is Credible",
    description: "Purdue University Global's comprehensive checklist to help evaluate the credibility of academic sources.",
    URL: "https://www.purdueglobal.edu/blog/online-learning/credible-academic-sources",
    rating: 2,
  },
  {
    competency: "Digital Information Literacy",
    level: "knowledge",
    title: "Evaluating Web Sources",
    description: "Harvard University's guidelines for critically assessing the credibility of online information.",
    URL: "https://library.ed.ac.uk/finding-resources/databases-overview/evaluating-websites",
    rating: 3,
  },
  {
    competency: "Digital Information Literacy",
    level: "knowledge",
    title: "How to Improve Accuracy in the Workplace",
    description: "Discusses strategies to enhance accuracy in professional settings, emphasising its impact on business success.",
    URL: "https://bizfluent.com/how-10032968-improve-accuracy-workplace.html",
    rating: 4,
  },
  {
    competency: "Digital Information Literacy",
    level: "knowledge",
    title: "Why Attention to Detail is Important in the Workplace",
    description: "Explores the significance of meticulousness in work tasks and its effect on overall performance and quality.",
    URL: "https://www.testpartnership.com/blog/why-attention-to-detail-important.html",
    rating: 5,
  },
  {
    competency: "Digital Information Literacy",
    level: "skills",
    title: "Best Practices To Keep Your Shared Files Organised",
    description: "Provides strategies for structuring shared files, including building a well-planned folder hierarchy and implementing consistent naming conventions.",
    URL: "https://www.worksmart.com/best-practices-to-keep-your-shared-files-organized-plus-end-user-tips/",
    rating: 1,
  },
  {
    competency: "Digital Information Literacy",
    level: "skills",
    title: "11 Ideas for How to Organise Digital Files",
    description: "Offers methods for organising digital files efficiently, such as sorting by name, date, project, or department, to enhance retrieval and management.",
    URL: "https://www.microsoft.com/en-us/microsoft-365/business-insights-ideas/resources/11-ideas-for-how-to-organize-digital-files",
    rating: 2,
  },
  {
    competency: "Digital Information Literacy",
    level: "skills",
    title: "Guide to Creating Effective File and Folder Naming Conventions",
    description: "Discusses the importance of consistent and meaningful file and folder naming conventions for organisational efficiency and improved searchability.",
    URL: "https://www.desoto.io/post/guide-to-creating-effective-file-and-folder-naming-conventions",
    rating: 3,
  },
  {
    competency: "Digital Information Literacy",
    level: "skills",
    title: "How to Share Information with Team Members Effectively",
    description: "Explores various methods for effective information sharing within teams, including the use of communication platforms and fostering a culture of open access.",
    URL: "https://clickup.com/blog/how-to-share-information-with-team-members/",
    rating: 4,
  },
  {
    competency: "Digital Information Literacy",
    level: "skills",
    title: "Best Practices for File Naming and Organising",
    description: "Provides guidelines on naming and organising files to indicate their contents and specify relationships to other files, enhancing clarity and accessibility.",
    URL: "https://library.si.edu/sites/default/files/tutorial/pdf/filenamingorganizing20180227.pdf",
    rating: 5,
  },
  {
    competency: "Digital Information Literacy",
    level: "attitudes",
    title: "Fact-Checking: The Importance of Verifying Information in Today's Digital Age",
    description: "Discusses the necessity of fact-checking to ensure the accuracy of information shared, highlighting the ethical and legal implications of disseminating false data.",
    URL: "https://www.alphapublisher.com/post/fact-checking-the-importance-of-verifying-information-in-today-s-digital-age",
    rating: 1,
  },
  {
    competency: "Digital Information Literacy",
    level: "attitudes",
    title: "9 Approaches to Fact-Checking and Verification",
    description: "Provides strategies for verifying information, including consulting credible sources and corroborating key facts, to maintain accuracy in data sharing.",
    URL: "https://www.poynter.org/educators-students/2017/9-ways-to-verify-information/",
    rating: 2,
  },
  {
    competency: "Digital Information Literacy",
    level: "attitudes",
    title: "What is Data Accuracy? Definition, Importance, and Best Practices",
    description: "Explores the concept of data accuracy, its significance in business operations, and practices to ensure data integrity and reliability.",
    URL: "https://dataladder.com/what-is-data-accuracy/",
    rating: 3,
  },
  {
    competency: "Digital Information Literacy",
    level: "attitudes",
    title: "Understanding Data Quality: Accuracy, Reliability, and Consistency",
    description: "Examines the dimensions of data quality, emphasising the critical role of accuracy and reliability in effective decision-making.",
    URL: "https://www.bigdataframework.org/knowledge/understanding-data-quality/",
    rating: 4,
  },
  {
    competency: "Digital Information Literacy",
    level: "attitudes",
    title: "Why High-Quality and Relevant Data Is Essential in Today's Business Landscape",
    description: "Highlights the importance of accurate and relevant data in driving informed business decisions and maintaining operational efficiency.",
    URL: "https://www.forbes.com/councils/forbestechcouncil/2023/04/17/why-high-quality-and-relevant-data-is-essential-in-todays-business-landscape/",
    rating: 5,
  },

  {
    competency: "Digital Communication and Collaboration",
    level: "knowledge",
    title: "A Guide to Choosing the Right Communication Tool",
    description: "Explains how to select the best digital tool for various communication needs, from emails to instant messaging and video conferencing.",
    URL: "https://www.gettalkative.com/info/communication-channels",
    rating: 1,
  },
  {
    competency: "Digital Communication and Collaboration",
    level: "knowledge",
    title: "Effective Communication in the Workplace",
    description: "Discusses the importance of clear and respectful communication in professional settings, emphasising active listening and empathy.",
    URL: "https://www.careeraddict.com/the-importance-of-effective-communication-in-the-workplace",
    rating: 2,
  },
  {
    competency: "Digital Communication and Collaboration",
    level: "knowledge",
    title: "Communication Escalation: When and How to Act",
    description: "Provides guidance on recognising situations requiring escalation and offers best practices for effective communication with supervisors and stakeholders.",
    URL: "https://extension.psu.edu/effective-communication-in-the-workplace",
    rating: 3,
  },
  {
    competency: "Digital Communication and Collaboration",
    level: "knowledge",
    title: "Digital Tools for Professional Communication",
    description: "Covers various digital communication tools, their strengths, and when to use them for optimal communication in different professional scenarios.",
    URL: "https://www.microsoft.com/en-us/microsoft-365/business-insights-ideas",
    rating: 4,
  },
  {
    competency: "Digital Communication and Collaboration",
    level: "knowledge",
    title: "Mastering Workplace Communication Strategies",
    description: "Offers advanced strategies for managing professional communication, including escalation protocols and resolving workplace conflicts diplomatically.",
    URL: "https://hbr.org/2024/02/mastering-workplace-communication-strategies",
    rating: 5,
  },
  {
    competency: "Digital Communication and Collaboration",
    level: "skills",
    title: "28 Power User Tips for Microsoft Teams",
    description: "Offers advanced tips for effectively utilising Microsoft Teams, including organising teams and channels, managing notifications, and integrating with other tools.",
    URL: "https://www.computerworld.com/article/1714753/microsoft-teams-tips-and-tricks.html",
    rating: 1,
  },
  {
    competency: "Digital Communication and Collaboration",
    level: "skills",
    title: "10 Keys to Effective Business Writing",
    description: "Provides guidelines for writing clear, concise, and respectful business messages, emphasising the importance of clarity and brevity in professional communication.",
    URL: "https://www.grammarly.com/blog/business-writing/keys-to-effective-business-writing/",
    rating: 2,
  },
  {
    competency: "Digital Communication and Collaboration",
    level: "skills",
    title: "6 Tips for How to Communicate Clearly in Business",
    description: "Discusses strategies for clear and concise business communication, including focusing on the audience, organising thoughts, and avoiding jargon.",
    URL: "https://magazine.wharton.upenn.edu/digital/6-tips-for-clear-and-concise-business-communication/",
    rating: 3,
  },
  {
    competency: "Digital Communication and Collaboration",
    level: "skills",
    title: "How to Use Microsoft Teams Effectively",
    description: "Explores best practices for using Microsoft Teams, such as organising channels, managing notifications, and integrating with other Microsoft 365 apps.",
    URL: "https://www.process.st/how-to/use-microsoft-teams-effectively/",
    rating: 4,
  },
  {
    competency: "Digital Communication and Collaboration",
    level: "skills",
    title: "6 Steps to Keeping Your Emails Short and to the Point",
    description: "Offers practical advice on writing concise emails, including focusing on key points, using bullet points, and avoiding unnecessary information.",
    URL: "https://www.grammarly.com/blog/emailing/concise-email-writing/",
    rating: 5,
  },
  {
    competency: "Digital Communication and Collaboration",
    level: "attitudes",
    title: "Why Collaboration is Better Than Competition",
    description: "Discusses the importance of collaboration in creating innovative solutions and achieving collective success.",
    URL: "https://www.indeed.com/career-advice/career-development/why-is-collaboration-important",
    rating: 1,
  },
  {
    competency: "Digital Communication and Collaboration",
    level: "attitudes",
    title: "Why Collaboration in the Workplace is Important",
    description: "Explores how collaboration leads to better decision-making, problem-solving, and a more supportive team environment.",
    URL: "https://hbr.org/2017/07/why-collaboration-in-the-workplace-is-important",
    rating: 2,
  },
  {
    competency: "Digital Communication and Collaboration",
    level: "attitudes",
    title: "Fostering Teamwork: 5 Tips for Building Collaboration in Your Organisation",
    description: "Provides tips on how to create a collaborative work culture, including setting clear goals and fostering mutual respect.",
    URL: "https://www.forbes.com/sites/forbeshumanresourcescouncil/2023/01/10/fostering-teamwork-5-tips-for-building-collaboration/",
    rating: 3,
  },
  {
    competency: "Digital Communication and Collaboration",
    level: "attitudes",
    title: "The Power of Professionalism: Why It Matters",
    description: "Explores the importance of professionalism in workplace communication, including maintaining respect and effective interaction.",
    URL: "https://www.thehrdigest.com/professionalism-in-the-workplace-building-a-positive-environment/",
    rating: 4,
  },
  {
    competency: "Digital Communication and Collaboration",
    level: "attitudes",
    title: "Professionalism in the Workplace: A Guide for Employees",
    description: "Provides a comprehensive guide on how to maintain professionalism, including clear communication and respectful behaviour.",
    URL: "https://www.indeed.com/career-advice/career-development/workplace-professionalism",
    rating: 5,
  },

  {
    competency: "Cybersecurity and Data Protection",
    level: "knowledge",
    title: "Privacy & Data Protection",
    description: "Policies & Documentation, Training and Awareness Material",
    URL: "https://aswatsonuk.sharepoint.com/sites/Privacy",
    rating: 1,
  },
  {
    competency: "Cybersecurity and Data Protection",
    level: "knowledge",
    title: "How to Recognise and Avoid Phishing Scams",
    description: "Tips on spotting phishing emails and text messages, and advice on reporting them to help combat scammers.",
    URL: "https://consumer.ftc.gov/articles/how-recognize-and-avoid-phishing-scams",
    rating: 2,
  },
  {
    competency: "Cybersecurity and Data Protection",
    level: "knowledge",
    title: "How to Handle Sensitive Information or Records Securely",
    description: "Best practices for managing sensitive data, including classification, storage, and secure sharing protocols.",
    URL: "https://www.redactable.com/blog/how-to-handle-sensitive-information-or-records-securely",
    rating: 3,
  },
  {
    competency: "Cybersecurity and Data Protection",
    level: "knowledge",
    title: "How to Protect Sensitive Data: Your Risks and Responsibilities",
    description: "Discusses the importance of securing sensitive data and outlines responsibilities for organisations and individuals.",
    URL: "https://www.sikich.com/insight/how-to-protect-sensitive-data-your-risks-and-responsibilities/",
    rating: 4,
  },
  {
    competency: "Cybersecurity and Data Protection",
    level: "knowledge",
    title: "9 Best Practices to Manage Sensitive Data Carefully",
    description: "Provides strategies for handling sensitive data, including encryption, backups, and access controls.",
    URL: "https://www.duocircle.com/email-security/9-best-practices-to-manage-sensitive-data-carefully",
    rating: 5,
  },
  {
    competency: "Cybersecurity and Data Protection",
    level: "skills",
    title: "Cyber Ready",
    description: "If you suspect a Cyber Security incident (e.g. a potential data leak), you can become a Cyber Hero by reporting the incident. How do you do that? All information about how to report a potential security incident can be found on this page.",
    URL: "https://aswatsonuk.sharepoint.com/sites/ASWCyberSecurity/SitePages/Cyber-Ready-Program---General.aspx",
    rating: 1,
  },
  {
    competency: "Cybersecurity and Data Protection",
    level: "skills",
    title: "The Top 5 Cybersecurity Threats and How to Defend Against Them",
    description: "Discusses prevalent cybersecurity threats like ransomware and phishing, with strategies for defence.",
    URL: "https://www.isaca.org/resources/news-and-trends/industry-news/2024/the-top-5-cybersecurity-threats-and-how-to-defend-against-them?utm_source=chatgpt.com",
    rating: 2,
  },
  {
    competency: "Cybersecurity and Data Protection",
    level: "skills",
    title: "Phishing and How to Prevent It",
    description: "Explains phishing attacks and shares prevention techniques and best practices.",
    URL: "https://www.csoonline.com/article/3688015/phishing-attack-strategies-how-to-prevent-it.html",
    rating: 3,
  },
  {
    competency: "Cybersecurity and Data Protection",
    level: "skills",
    title: "How to Handle Sensitive Data Securely",
    description: "Offers strategies for securely handling sensitive data, from encryption to secure sharing.",
    URL: "https://www.sikich.com/insight/how-to-handle-sensitive-data-securely?utm_source=chatgpt.com",
    rating: 4,
  },
  {
    competency: "Cybersecurity and Data Protection",
    level: "skills",
    title: "How to Recognise and Avoid Phishing Scams",
    description: "A comprehensive guide on recognising phishing scams and how to protect against them.",
    URL: "https://www.ftc.gov/articles/how-recognize-and-avoid-phishing-scams?utm_source=chatgpt.com",
    rating: 5,
  },
  {
    competency: "Cybersecurity and Data Protection",
    level: "attitudes",
    title: "The Business of Cybersecurity Ownership",
    description: "Discusses the importance of taking ownership of cybersecurity across an organisation and how every employee plays a role in protecting assets.",
    URL: "https://www.rapid7.com/blog/post/2024/05/01/the-business-of-cybersecurity-ownership/?utm_source=chatgpt.com",
    rating: 1,
  },
  {
    competency: "Cybersecurity and Data Protection",
    level: "attitudes",
    title: "Creating a Culture of Security Awareness",
    description: "Explores strategies for instilling a culture of vigilance and proactive cybersecurity among employees.",
    URL: "https://www.cybernod.com/blog/building-a-culture-of-security-awareness/?utm_source=chatgpt.com",
    rating: 2,
  },
  {
    competency: "Cybersecurity and Data Protection",
    level: "attitudes",
    title: "Building a Cybersecurity Conscious Organisation",
    description: "Provides best practices for organisations to take ownership of cybersecurity by empowering all employees to protect company data.",
    URL: "https://www.businessnewsdaily.com/8225-cybersecurity-awareness-workplace.html?utm_source=chatgpt.com",
    rating: 3,
  },
  {
    competency: "Cybersecurity and Data Protection",
    level: "attitudes",
    title: "The Role of Cybersecurity Training in Vigilance",
    description: "Explains how continuous training and awareness programmes can help employees stay vigilant and spot potential cybersecurity threats.",
    URL: "https://www.securityintelligence.com/articles/how-cybersecurity-training-helps-your-team-detect-threats/?utm_source=chatgpt.com",
    rating: 4,
  },
  {
    competency: "Cybersecurity and Data Protection",
    level: "attitudes",
    title: "Keeping Employees Vigilant Against Cyber Threats",
    description: "Focuses on maintaining employee vigilance against cybersecurity threats through engagement and simulation exercises.",
    URL: "https://www.privacy.com/keeping-employees-vigilant-against-cyber-threats?utm_source=chatgpt.com",
    rating: 5,
  },

  {
    competency: "Digital Ethics and Compliance",
    level: "knowledge",
    title: "The Importance of Data Usage Policies in Organisations",
    description: "Introduces the concept of data usage policies and their role in safeguarding company data, with a focus on basic practices.",
    URL: "https://www.cio.com/article/3614749/the-importance-of-data-usage-policies-in-business?utm_source=chatgpt.com",
    rating: 1,
  },
  {
    competency: "Digital Ethics and Compliance",
    level: "knowledge",
    title: "How Ethical Considerations in Digital Interactions Affect Your Business",
    description: "Explains ethical considerations in digital interactions, emphasising privacy and transparency in communication.",
    URL: "https://link.springer.com/article/10.1007/s11245-021-09792-9?utm_source=chatgpt.com",
    rating: 2,
  },
  {
    competency: "Digital Ethics and Compliance",
    level: "knowledge",
    title: "Data Protection Best Practices for Organisations",
    description: "Discusses best practices for data protection, focusing on the basics of securing data and ensuring compliance with industry standards.",
    URL: "https://www.dataversity.net/the-role-of-data-protection-and-privacy-in-compliance/?utm_source=chatgpt.com",
    rating: 3,
  },
  {
    competency: "Digital Ethics and Compliance",
    level: "knowledge",
    title: "Digital Ethics and Responsibility in the Workplace",
    description: "Provides an overview of digital ethics, focusing on responsibility and integrity in digital business environments.",
    URL: "https://www.cio.com/article/285758/digital-ethics-and-responsibility-in-the-workplace?utm_source=chatgpt.com",
    rating: 4,
  },
  {
    competency: "Digital Ethics and Compliance",
    level: "knowledge",
    title: "Navigating Compliance with Data Protection Regulations",
    description: "An in-depth look at compliance with data protection regulations like GDPR, providing strategies for organisations to meet legal and ethical standards.",
    URL: "https://www.sans.org/cyber-security-solutions/compliance-data-protection/?utm_source=chatgpt.com",
    rating: 5,
  },
  {
    competency: "Digital Ethics and Compliance",
    level: "skills",
    title: "Best Ethical Practices in Technology",
    description: "Provides guidance on the ethical practices for using digital tools, including privacy, transparency, and responsible behaviour.",
    URL: "https://www.scu.edu/ethics-in-technology-practice/best-ethical-practices-in-technology/?utm_source=chatgpt.com",
    rating: 1,
  },
  {
    competency: "Digital Ethics and Compliance",
    level: "skills",
    title: "Reporting Unethical Behaviour in the Workplace",
    description: "Discusses the steps to recognise and report unethical behaviour, including the use of company-established reporting channels.",
    URL: "https://work.chron.com/report-unethical-behavior-workplace-19752.html?utm_source=chatgpt.com",
    rating: 2,
  },
  {
    competency: "Digital Ethics and Compliance",
    level: "skills",
    title: "What to Do if You Suspect Unethical Activity at Work",
    description: "Offers advice on how to report unethical actions at work and outlines protections for whistleblowers.",
    URL: "https://rpc.cfainstitute.org/en/research/cfa-magazine/2017/what-to-do-if-you-suspect-unethical-activity-is-happening-at-work?utm_source=chatgpt.com",
    rating: 3,
  },
  {
    competency: "Digital Ethics and Compliance",
    level: "skills",
    title: "How to Implement Compliance Processes in Your Company",
    description: "Explains how employees can effectively implement company compliance processes and monitor adherence to legal and ethical standards.",
    URL: "https://rpc.cfainstitute.org/en/research/cfa-magazine/2017/what-to-do-if-you-suspect-unethical-activity-is-happening-at-work?utm_source=chatgpt.com",
    rating: 4,
  },
  {
    competency: "Digital Ethics and Compliance",
    level: "skills",
    title: "The Importance of Company Compliance Programmes",
    description: "Focuses on the importance of adhering to company compliance programmes and the role of employees in supporting these processes.",
    URL: "https://www.investopedia.com/terms/c/compliance-program.asp?utm_source=chatgpt.com",
    rating: 5,
  },
  {
    competency: "Digital Ethics and Compliance",
    level: "attitudes",
    title: "What Is Confidentiality and Why Is It Important?",
    description: "A beginner-friendly explanation of confidentiality, why it matters in the workplace, and the basics of safeguarding sensitive information.",
    URL: "https://www.businessnewsdaily.com/15156-importance-of-confidentiality.html?utm_source=chatgpt.com",
    rating: 1,
  },
  {
    competency: "Digital Ethics and Compliance",
    level: "attitudes",
    title: "The Basics of Ethical Conduct in Digital Spaces",
    description: "An introductory guide to understanding digital ethics, including how to use tools responsibly and demonstrate integrity.",
    URL: "https://www.businessnewsdaily.com/15156-ethical-behavior-in-the-workplace.html?utm_source=chatgpt.com",
    rating: 2,
  },
  {
    competency: "Digital Ethics and Compliance",
    level: "attitudes",
    title: "How to Protect Sensitive Information at Work",
    description: "Offers fundamental steps for protecting sensitive data in the workplace, including encryption and limiting access.",
    URL: "https://www.cio.com/article/286135/how-to-protect-sensitive-information-at-work.html?utm_source=chatgpt.com",
    rating: 3,
  },
  {
    competency: "Digital Ethics and Compliance",
    level: "attitudes",
    title: "Understanding Digital Ethics and Responsibility",
    description: "Explains the importance of integrity and ethical behaviour in digital activities, with practical examples.",
    URL: "https://www.cio.com/article/285758/digital-ethics-and-responsibility-in-the-workplace?utm_source=chatgpt.com",
    rating: 4,
  },
  {
    competency: "Digital Ethics and Compliance",
    level: "attitudes",
    title: "Building a Culture of Integrity and Accountability",
    description: "In-depth guidance on fostering a workplace culture focused on integrity, responsibility, and ethical conduct in digital practices.",
    URL: "https://www.forbes.com/sites/forbeshumanresourcescouncil/2024/01/21/building-a-culture-of-integrity-and-accountability-in-the-workplace?utm_source=chatgpt.com",
    rating: 5,
  },

  {
    competency: "Digital Well-being and Sustainability",
    level: "knowledge",
    title: "How Screen Time Affects Your Health",
    description: "Explains how excessive screen time can negatively impact mental and physical health, with tips for reducing screen use.",
    URL: "https://health.osu.edu/health/mental-health/how-screen-time-affects-your-health?utm_source=chatgpt.com",
    rating: 1,
  },
  {
    competency: "Digital Well-being and Sustainability",
    level: "knowledge",
    title: "What Excessive Screen Time Does to Your Brain",
    description: "Discusses the cognitive and physical effects of prolonged screen exposure and provides advice on mitigating its impacts.",
    URL: "https://longevity.stanford.edu/lifestyle/2024/05/30/what-excessive-screen-time-does-to-the-adult-brain/?utm_source=chatgpt.com",
    rating: 2,
  },
  {
    competency: "Digital Well-being and Sustainability",
    level: "knowledge",
    title: "The Digital Footprint and Its Environmental Impact",
    description: "Focuses on the environmental footprint of digital activities, such as energy consumption in data centres and e-waste.",
    URL: "https://greencitizen.com/blog/digital-carbon-footprint/?utm_source=chatgpt.com",
    rating: 3,
  },
  {
    competency: "Digital Well-being and Sustainability",
    level: "knowledge",
    title: "The Digital Footprint: How Technology Impacts the Environment",
    description: "Discusses how digital activities contribute to environmental degradation and ways to minimise impact, including reducing e-waste.",
    URL: "https://emagazine.com/the-digital-footprint-how-technology-impacts-the-environment-and-what-you-can-do-to-help/?utm_source=chatgpt.com",
    rating: 4,
  },
  {
    competency: "Digital Well-being and Sustainability",
    level: "knowledge",
    title: "How to Maintain a Balance Between Technology Use and Well-being",
    description: "Provides strategies for maintaining a healthy balance between work, technology use, and personal life, including the importance of digital detox.",
    URL: "https://www.psychologytoday.com/us/blog/mental-health-matters/2024/how-to-maintain-a-balance-between-technology-and-well-being?utm_source=chatgpt.com",
    rating: 5,
  },
  {
    competency: "Digital Well-being and Sustainability",
    level: "skills",
    title: "Managing Screen Time for a Balanced Life",
    description: "Offers tips on how to manage screen time, including setting boundaries and taking regular breaks to reduce screen exposure and improve well-being.",
    URL: "https://youate.com/tips/digital-wellness-managing-screen-time-for-a-balanced-life/?utm_source=chatgpt.com",
    rating: 1,
  },
  {
    competency: "Digital Well-being and Sustainability",
    level: "skills",
    title: "How to Manage Screen Time and Prevent Overload",
    description: "Discusses strategies for managing screen time effectively, including using the 20-20-20 rule and incorporating physical activity.",
    URL: "https://real-resilience.co.uk/managing-screen-time-and-preventing-overload/?utm_source=chatgpt.com",
    rating: 2,
  },
  {
    competency: "Digital Well-being and Sustainability",
    level: "skills",
    title: "7 Tips for Managing Digital Workload",
    description: "Provides practical strategies for balancing digital workload, setting priorities, and managing screen time to avoid overload.",
    URL: "https://digitalzenlife.com/managing-screen-time-during-work-7-best/?utm_source=chatgpt.com",
    rating: 3,
  },
  {
    competency: "Digital Well-being and Sustainability",
    level: "skills",
    title: "How to Minimise E-Waste in the Digital Age",
    description: "Offers advice on reducing e-waste, such as extending the life of devices and using certified e-waste recyclers.",
    URL: "https://unsustainablemagazine.com/minimizing-e-waste-in-digital-age/?utm_source=chatgpt.com",
    rating: 4,
  },
  {
    competency: "Digital Well-being and Sustainability",
    level: "skills",
    title: "How to Reduce E-Waste and Choose Sustainable Devices",
    description: "Focuses on choosing energy-efficient and environmentally friendly devices, as well as recycling e-waste responsibly.",
    URL: "https://vox.com/technology/389775/ewaste-electronics-recycling-tech?utm_source=chatgpt.com",
    rating: 5,
  },
  {
    competency: "Digital Well-being and Sustainability",
    level: "attitudes",
    title: "How to Develop a Healthier Relationship with Technology",
    description: "Discusses how to set boundaries with technology, incorporate regular breaks, and engage in physical activity to maintain a healthy relationship with tech.",
    URL: "https://www.psychologytoday.com/us/blog/the-science-of-stuck/202309/how-to-develop-a-healthier-relationship-with-technology?utm_source=chatgpt.com",
    rating: 1,
  },
  {
    competency: "Digital Well-being and Sustainability",
    level: "attitudes",
    title: "The Importance of Setting Boundaries with Technology",
    description: "Explains the importance of setting boundaries and prioritising time away from screens to foster a healthy balance between technology and personal life.",
    URL: "https://www.psychologytoday.com/us/blog/the-science-of-stuck/202309/how-to-develop-a-healthier-relationship-with-technology?utm_source=chatgpt.com",
    rating: 2,
  },
  {
    competency: "Digital Well-being and Sustainability",
    level: "attitudes",
    title: "The 7 Golden Rules for a Sustainable Digital Workplace",
    description: "Offers practical steps for making digital practices more sustainable, including extending device lifespan and reducing energy consumption.",
    URL: "https://www.wavestone.com/en/insight/7-golden-rules-sustainable-digital-workplace/?utm_source=chatgpt.com",
    rating: 3,
  },
  {
    competency: "Digital Well-being and Sustainability",
    level: "attitudes",
    title: "How to Reduce E-Waste and Encourage Sustainable Digital Practices",
    description: "Focuses on how to reduce e-waste, repair devices, and adopt eco-friendly digital practices for sustainability.",
    URL: "https://www.wavestone.com/en/insight/7-golden-rules-sustainable-digital-workplace/?utm_source=chatgpt.com",
    rating: 4,
  },
  {
    competency: "Digital Well-being and Sustainability",
    level: "attitudes",
    title: "Choosing Energy-Efficient Digital Tools and Devices",
    description: "Discusses the importance of selecting energy-efficient devices and promoting sustainable digital habits.",
    URL: "https://www.wavestone.com/en/insight/7-golden-rules-sustainable-digital-workplace/?utm_source=chatgpt.com",
    rating: 5,
  },

  {
    competency: "AI and Digital Tools",
    level: "knowledge",
    title: "Digital Tools 101: A Beginner's Guide",
    description: "Introduces the basic features and purposes of common workplace digital tools like email and spreadsheets.",
    URL: "https://www.digitalstarterkit.com/beginners-guide-to-digital-tools",
    rating: 1,
  },
  {
    competency: "AI and Digital Tools",
    level: "knowledge",
    title: "Understanding the Basics of Digital Tools",
    description: "Explains the core functions of widely used tools such as Microsoft Office and Google Workspace.",
    URL: "https://www.digitalbasics.org/understanding-digital-tools",
    rating: 2,
  },
  {
    competency: "AI and Digital Tools",
    level: "knowledge",
    title: "How to Use Technology to Improve Efficiency",
    description: "Provides insights into optimising workflows using tools like project management software and automation.",
    URL: "https://www.forbes.com/councils/forbesbusinesscouncil/increasing-operational-efficiency-with-technology",
    rating: 3,
  },
  {
    competency: "AI and Digital Tools",
    level: "knowledge",
    title: "When to Seek Help with Digital Tools",
    description: "Highlights scenarios where seeking assistance can enhance the use of complex digital tools effectively.",
    URL: "https://www.techhelp.org/when-to-seek-help-with-digital-tools",
    rating: 4,
  },
  {
    competency: "AI and Digital Tools",
    level: "knowledge",
    title: "Expert Strategies for Digital Tool Optimisation",
    description: "Provides expert-level advice on integrating multiple digital tools and customising workflows for peak efficiency.",
    URL: "https://www.digitalsolutions.com/expert-strategies-for-tool-optimization",
    rating: 5,
  },
  {
    competency: "AI and Digital Tools",
    level: "skills",
    title: "Beginner's Guide to Digital Tools and AI Features",
    description: "Introduces essential digital tools and simple AI applications for newcomers.",
    URL: "https://www.techstarterkit.com/beginners-guide-to-digital-tools-and-ai-features",
    rating: 1,
  },
  {
    competency: "AI and Digital Tools",
    level: "skills",
    title: "Learn AI Fundamentals with Google AI Essentials",
    description: "Offers foundational knowledge and practical exercises for understanding and applying AI features in common tools.",
    URL: "https://www.grow.google/ai-essentials",
    rating: 2,
  },
  {
    competency: "AI and Digital Tools",
    level: "skills",
    title: "Common Software Problems and How You Can Fix Them",
    description: "Identifies frequent software issues and offers practical solutions to help users maintain productivity and confidence.",
    URL: "https://www.programmers.io/blog/how-to-fix-common-software-issues",
    rating: 3,
  },
  {
    competency: "AI and Digital Tools",
    level: "skills",
    title: "The Ultimate Guide to Troubleshooting Software Issues: Key Techniques",
    description: "Offers comprehensive techniques for diagnosing and resolving advanced software problems, empowering users to troubleshoot effectively.",
    URL: "https://www.techjournal.org/the-ultimate-guide-to-troubleshooting-software-issues-key-techniques",
    rating: 4,
  },
  {
    competency: "AI and Digital Tools",
    level: "skills",
    title: "Advanced Features in Digital Tools: Expert Techniques",
    description: "Focuses on using advanced functionalities in digital tools and AI to optimise workflows and achieve maximum productivity.",
    URL: "https://www.digitalsolutions.com/advanced-features-in-digital-tools",
    rating: 5,
  },
  {
    competency: "AI and Digital Tools",
    level: "attitudes",
    title: "Getting Started with Digital Tools: A Beginner's Guide",
    description: "Provides an introduction to basic digital tools and the mindset needed for learning new technologies like Microsoft Copilot.",
    URL: "https://www.digitalstarterkit.com/getting-started-with-digital-tools",
    rating: 1,
  },
  {
    competency: "AI and Digital Tools",
    level: "attitudes",
    title: "Encouraging a Culture of Digital Learning",
    description: "Offers practical steps to motivate colleagues to improve their digital skills and adopt new features gradually.",
    URL: "https://www.motivationhq.com/encouraging-digital-learning",
    rating: 2,
  },
  {
    competency: "AI and Digital Tools",
    level: "attitudes",
    title: "How to Promote Digital Literacy at Your Organisation",
    description: "Discusses strategies for promoting digital literacy among employees, including fostering openness to learning and sharing knowledge.",
    URL: "https://www.peoplekeep.com/blog/how-to-promote-digital-literacy",
    rating: 3,
  },
  {
    competency: "AI and Digital Tools",
    level: "attitudes",
    title: "Digital Upskilling Strategies for Transformative Success",
    description: "Explores advanced strategies to help employees adopt new digital tools and features effectively while fostering a collaborative culture.",
    URL: "https://www.datacamp.com/blog/digital-upskilling-strategies-for-transformative-success",
    rating: 4,
  },
  {
    competency: "AI and Digital Tools",
    level: "attitudes",
    title: "Unlocking Copilot Adoption: Strategies for Successful Tech Integration",
    description: "Focuses on expert strategies for integrating advanced tools like Microsoft Copilot, including training and team enablement.",
    URL: "www.learn.microsoft.com/en-us/shows/copilot-learning-hub/unlocking-copilot-adoption-strategies-for-successful-tech-integration",
    rating: 5,
  },

  {
    competency: "Adaptability and Continuous Learning",
    level: "knowledge",
    title: "Continuous Learning in the Digital Age",
    description: "Explores the necessity of lifelong learning for personal and professional growth in a rapidly changing digital environment.",
    URL: "https://edtechist.co.uk/continuous-learning-in-the-digital-age/",
    rating: 1,
  },
  {
    competency: "Adaptability and Continuous Learning",
    level: "knowledge",
    title: "Why Adaptability is the New Digital Transformation",
    description: "Discusses how adaptability has become crucial for successful digital transformation, emphasising the need for flexibility in organisational strategies.",
    URL: "https://wginc.com/why-adaptability-is-the-new-digital-transformation/",
    rating: 2,
  },
  {
    competency: "Adaptability and Continuous Learning",
    level: "knowledge",
    title: "The Importance of Continuous Learning in the Digital Age",
    description: "Highlights the significance of ongoing skill development to remain relevant and competitive in today's fast-paced digital world.",
    URL: "https://inclinemagazine.com/the-importance-of-continuous-learning-in-the-digital-age/",
    rating: 3,
  },
  {
    competency: "Adaptability and Continuous Learning",
    level: "knowledge",
    title: "Future Proof: Solving the Adaptability Paradox for the Long Term",
    description: "Examines the role of adaptability in long-term success, offering insights into building resilience and flexibility in the face of continuous change.",
    URL: "https://www.mckinsey.com/capabilities/people-and-organizational-performance/our-insights/future-proof-solving-the-adaptability-paradox-for-the-long-term",
    rating: 4,
  },
  {
    competency: "Adaptability and Continuous Learning",
    level: "knowledge",
    title: "Learning in the Digital Age",
    description: "Provides strategies for fostering a culture of continuous learning within organisations, leveraging digital tools and platforms.",
    URL: "https://www2.deloitte.com/us/en/insights/focus/human-capital-trends/2017/learning-in-the-digital-age.html",
    rating: 5,
  },
  {
    competency: "Adaptability and Continuous Learning",
    level: "skills",
    title: "How to Be Flexible in the Workplace",
    description: "In this article, we explain what it means to be flexible, how it can benefit you, and how you can achieve it",
    URL: "https://prime.mindtools.com/pages/article/flexibility-at-work.htm",
    rating: 1,
  },
  {
    competency: "Adaptability and Continuous Learning",
    level: "skills",
    title: "How to Acquire New Skills in 10 Steps",
    description: "Outlines clear, beginner-friendly steps to help employees acquire and apply new skills effectively.",
    URL: "https://www.indeed.com/career-advice/career-development/acquire-skills",
    rating: 2,
  },
  {
    competency: "Adaptability and Continuous Learning",
    level: "skills",
    title: "How To Apply Knowledge And Skills At Work: 5 Simple Ways",
    description: "Explains practical ways to implement newly learned skills into day-to-day work tasks.",
    URL: "https://www.futuredecider.com/how-to-apply-knowledge-and-skills-at-work",
    rating: 3,
  },
  {
    competency: "Adaptability and Continuous Learning",
    level: "skills",
    title: "13 Practical Ways To Help Employees Adapt To New Technology",
    description: "Provides strategies for adapting to new processes, including understanding their purpose and seeking feedback to improve implementation.",
    URL: "https://www.forbes.com/councils/forbeshumanresourcescouncil/13-practical-ways-to-help-employees-adapt-to-new-technology",
    rating: 4,
  },
  {
    competency: "Adaptability and Continuous Learning",
    level: "skills",
    title: "8 Strategies To Help Employees Adapt to New Technology in the Workplace",
    description: "Focuses on advanced strategies like involving employees in change decisions and offering structured training for maximum adaptability.",
    URL: "https://www.spiceworks.com/hr/future-work/guest-article/8-strategies-to-help-employees-adapt-to-new-technology-in-the-workplace",
    rating: 5,
  },
  {
    competency: "Adaptability and Continuous Learning",
    level: "attitudes",
    title: "Embracing Change: The Power of a Positive Attitude",
    description: "Discusses the importance of adopting a positive mindset toward change and offers strategies to turn potential obstacles into opportunities for growth.",
    URL: "https://www.claudejobin.com/embracing-change-the-power-of-a-positive-attitude/",
    rating: 1,
  },
  {
    competency: "Adaptability and Continuous Learning",
    level: "attitudes",
    title: "14 Ways to Embrace and Accept Change in Your Life",
    description: "Provides practical tips for accepting and embracing change, including determining the value of change and easing into it to make transitions more manageable.",
    URL: "https://www.forbes.com/sites/forbescoachescouncil/2019/11/20/14-ways-to-embrace-and-accept-change-in-your-life/",
    rating: 2,
  },
  {
    competency: "Adaptability and Continuous Learning",
    level: "attitudes",
    title: "8 'Be-Attitudes' to Embrace Change and Increase Adaptability",
    description: "Offers attitudes to adopt for better adaptability, such as being flexible and viewing change as an opportunity for improvement.",
    URL: "https://ocdalecarnegie.com/8-be-attitudes-to-embrace-change-and-increase-adaptability/",
    rating: 3,
  },
  {
    competency: "Adaptability and Continuous Learning",
    level: "attitudes",
    title: "Cultivate a Learning Culture Within Your Organisation",
    description: "Explores strategies to promote risk-taking, transparency, and continuous learning within teams, encouraging a culture where growth is valued.",
    URL: "https://www.ccl.org/articles/leading-effectively-articles/cultivate-and-sustain-a-learning-culture-within-your-organization/",
    rating: 4,
  },
  {
    competency: "Adaptability and Continuous Learning",
    level: "attitudes",
    title: "20 Ways Managers Can Create a Culture of Continuous Learning",
    description: "Provides innovative ideas and strategies for managers to implement and sustain a culture of continuous learning, empowering employees to learn enthusiastically.",
    URL: "https://www.forbes.com/sites/forbeshumanresourcescouncil/2024/01/05/20-ways-managers-can-create-a-culture-of-continuous-learning/",
    rating: 5,
  },

  {
    competency: "Data Literacy and Analytics",
    level: "knowledge",
    title: "Methods of Data Collection",
    description: "Provides an overview of various data collection methods, including surveys, interviews, and observations, essential for gathering accurate information.",
    URL: "https://www.geeksforgeeks.org/methods-of-data-collection/",
    rating: 1,
  },
  {
    competency: "Data Literacy and Analytics",
    level: "knowledge",
    title: "Data Interpretation: Basic Concepts, Process and Types Explained",
    description: "Explains the fundamentals of data interpretation, detailing processes and types to help in understanding and analysing collected data effectively.",
    URL: "https://unacademy.com/content/ssc/study-material/mathematics/data-interpretation/",
    rating: 2,
  },
  {
    competency: "Data Literacy and Analytics",
    level: "knowledge",
    title: "Data Collection",
    description: "Discusses systematic data collection processes, offering definitions, methods, and examples to ensure accurate and ethical data gathering.",
    URL: "https://www.scribbr.com/methodology/data-collection/",
    rating: 3,
  },
  {
    competency: "Data Literacy and Analytics",
    level: "knowledge",
    title: "Exploring 12 of the Best Data Visualisation Tools in 2023",
    description: "Reviews various data visualisation tools, highlighting their features and suitability for different analytical needs, aiding in informed tool selection.",
    URL: "https://www.datacamp.com/blog/12-of-the-best-data-visualizations-tools",
    rating: 4,
  },
  {
    competency: "Data Literacy and Analytics",
    level: "knowledge",
    title: "The Best Data Visualisation Tools Of 2024",
    description: "Evaluates top data visualisation tools, discussing their pros and cons to assist in choosing the right tool for data analysis and presentation.",
    URL: "https://www.forbes.com/advisor/business/software/best-data-visualization-tools/",
    rating: 5,
  },
  {
    competency: "Data Literacy and Analytics",
    level: "skills",
    title: "Data Visualization: How to Transform Analytics Data into Actionable Insights",
    description: "Explores methods to convert complex analytics data into clear, actionable insights using visualisation techniques, enhancing comprehension and decision-making.",
    URL: "https://martech.org/data-visualization-how-to-transform-analytics-data-into-actionable-insights/",
    rating: 1,
  },
  {
    competency: "Data Literacy and Analytics",
    level: "skills",
    title: "Turning Data Into Actionable Insights: A Step-By-Step Guide",
    description: "Provides a comprehensive guide on interpreting data to extract actionable insights, emphasising the importance of visualisation in presenting findings effectively.",
    URL: "https://www.essense.io/blog/turning-data-into-actionable-insights-a-step-by-step-guide",
    rating: 2,
  },
  {
    competency: "Data Literacy and Analytics",
    level: "skills",
    title: "How to Turn Insights Into Actionable Visuals with Data Visualization",
    description: "Discusses the process of creating impactful data visualisations that convey insights clearly, aiding in better decision-making and communication.",
    URL: "https://nmqdigital.com/blog/how-to-turn-insights-into-actionable-visuals-with-data-visualization",
    rating: 3,
  },
  {
    competency: "Data Literacy and Analytics",
    level: "skills",
    title: "Visualizing Success: Advanced Data Visualization Techniques for Business Insights",
    description: "Delves into sophisticated data visualisation techniques and tools that help businesses interpret data effectively and derive actionable insights.",
    URL: "https://www.park.edu/blog/visualizing-success-advanced-data-visualization-techniques-for-business-insights/",
    rating: 4,
  },
  {
    competency: "Data Literacy and Analytics",
    level: "skills",
    title: "Data Visualization Techniques to Turn Complex Data Sets into Clear Insights",
    description: "Examines various data visualisation methods to simplify complex data sets, enabling the extraction of clear, actionable insights for informed decision-making.",
    URL: "https://abmatic.ai/blog/data-visualization-techniques-to-turn-complex-data-sets-into-clear-insights",
    rating: 5,
  },
  {
    competency: "Data Literacy and Analytics",
    level: "attitudes",
    title: "Understanding Data Quality: Accuracy, Reliability, and Consistency",
    description: "Explores the critical aspects of data quality, emphasising the importance of accuracy and attention to detail in data analysis.",
    URL: "https://www.bigdataframework.org/knowledge/understanding-data-quality/",
    rating: 1,
  },
  {
    competency: "Data Literacy and Analytics",
    level: "attitudes",
    title: "Attention to Detail: 25 Performance Review Phrases Examples",
    description: "Provides examples highlighting the significance of meticulousness in professional settings, particularly in data-related tasks.",
    URL: "https://status.net/articles/attention-to-detail-performance-review-phrases-paragraphs-examples/",
    rating: 2,
  },
  {
    competency: "Data Literacy and Analytics",
    level: "attitudes",
    title: "Three Ways You Can Build A Data-Driven Culture",
    description: "Offers strategies to foster a data-centric environment within teams, promoting informed decision-making.",
    URL: "https://www.forbes.com/councils/forbestechcouncil/2024/10/15/three-ways-you-can-build-a-data-driven-culture/",
    rating: 3,
  },
  {
    competency: "Data Literacy and Analytics",
    level: "attitudes",
    title: "The Keys To Fostering A Data-Driven Culture",
    description: "Discusses essential elements for cultivating a data-driven culture, including leadership commitment and data literacy.",
    URL: "https://www.forbes.com/councils/forbesbusinesscouncil/2024/04/18/the-keys-to-fostering-a-data-driven-culture/",
    rating: 4,
  },
  {
    competency: "Data Literacy and Analytics",
    level: "attitudes",
    title: "Ten Steps To Creating A Data-Driven Culture",
    description: "Provides a comprehensive guide to embedding data-driven practices within an organisation, ensuring data integrity and effective utilisation.",
    URL: "https://www.oliverwyman.com/our-expertise/insights/2020/feb/ten-steps-to-creating-a-data-driven-culture.html",
    rating: 5,
  },

  {
    competency: "Digital Problem Solving",
    level: "knowledge",
    title: "Basic Troubleshooting Techniques",
    description: "Provides fundamental troubleshooting steps for common computer issues, including restarting devices and checking connections.",
    URL: "https://edu.gcfglobal.org/en/computerbasics/basic-troubleshooting-techniques/1/",
    rating: 1,
  },
  {
    competency: "Digital Problem Solving",
    level: "knowledge",
    title: "How to Solve the 10 Most Common Tech Support Problems Yourself",
    description: "Offers solutions to frequent technical problems, such as software errors and connectivity issues, empowering users to resolve them independently.",
    URL: "https://www.pcworld.com/article/447413/how-to-solve-the-10-most-common-tech-support-problems-yourself.html",
    rating: 2,
  },
  {
    competency: "Digital Problem Solving",
    level: "knowledge",
    title: "Managing IT Escalations: Three Essential Tips",
    description: "Discusses effective escalation management in IT support, emphasising the importance of clear procedures and collaboration among support teams.",
    URL: "https://community.atlassian.com/t5/App-Central-articles/Managing-IT-Escalations-Three-Essential-Tips/ba-p/2322802",
    rating: 3,
  },
  {
    competency: "Digital Problem Solving",
    level: "knowledge",
    title: "The Importance of an Information Technology Escalation Process",
    description: "Highlights the necessity of a well-defined escalation process in IT, detailing steps to assign priority levels and delegate responsibilities for efficient issue resolution.",
    URL: "https://www.praecipio.com/resources/articles/the-importance-of-an-information-technology-escalation-process",
    rating: 4,
  },
  {
    competency: "Digital Problem Solving",
    level: "knowledge",
    title: "Ticket Escalation Process: Steps, Best Practices, and Key Tips",
    description: "Provides a comprehensive guide on ticket escalation in IT service management, outlining procedures to ensure timely and efficient handling of complex issues.",
    URL: "https://thectoclub.com/topics/ticket-escalation-process-guide/",
    rating: 5,
  },
  {
    competency: "Digital Problem Solving",
    level: "skills",
    title: "Basic Troubleshooting Techniques",
    description: "Offers fundamental strategies for identifying and resolving common computer problems, emphasising the importance of systematic approaches.",
    URL: "https://edu.gcfglobal.org/en/computerbasics/basic-troubleshooting-techniques/1/",
    rating: 1,
  },
  {
    competency: "Digital Problem Solving",
    level: "skills",
    title: "How to Solve the 10 Most Common Tech Support Problems Yourself",
    description: "Provides solutions to frequent technical issues, empowering individuals to address problems independently and efficiently.",
    URL: "https://www.pcworld.com/article/447413/how-to-solve-the-10-most-common-tech-support-problems-yourself.html",
    rating: 2,
  },
  {
    competency: "Digital Problem Solving",
    level: "skills",
    title: "4 Steps to Troubleshooting (Almost) Any IT Issue",
    description: "Outlines a logical, step-by-step process for diagnosing and resolving IT problems, applicable to a wide range of technical challenges.",
    URL: "https://www.spiceworks.com/it-articles/troubleshooting-steps/",
    rating: 3,
  },
  {
    competency: "Digital Problem Solving",
    level: "skills",
    title: "Troubleshooting Made Simple: Tips for Tech Problem-Solving",
    description: "Discusses practical techniques for effective troubleshooting, including clear communication and systematic problem-solving methods.",
    URL: "https://www.allskilled.com/post/troubleshooting-made-simple-tips-for-tech-problem-solving",
    rating: 4,
  },
  {
    competency: "Digital Problem Solving",
    level: "skills",
    title: "How to Provide Meaningful Support to Coworkers and Build a Collaborative Environment",
    description: "Explores ways to assist colleagues with technical challenges, fostering a supportive and collaborative workplace culture.",
    URL: "https://carreersupport.com/helping-and-supporting-others-at-work/",
    rating: 5,
  },
  {
    competency: "Digital Problem Solving",
    level: "attitudes",
    title: "Don't Panic: Eight Strategies For Staying Calm When Your Technology Breaks",
    description: "Offers practical advice on maintaining composure during technical difficulties, emphasising the importance of calm leadership in resolving issues effectively.",
    URL: "https://www.forbes.com/sites/forbestechcouncil/2016/09/06/dont-panic-eight-strategies-for-staying-calm-when-your-technology-breaks/",
    rating: 1,
  },
  {
    competency: "Digital Problem Solving",
    level: "attitudes",
    title: "Experiencing Technical Difficulties? 14 Ways To Maintain Command Of A Virtual Room",
    description: "Provides strategies to remain composed and authoritative during virtual meetings facing technical challenges, ensuring effective communication and problem-solving.",
    URL: "https://www.forbes.com/sites/forbescoachescouncil/2020/10/23/experiencing-technical-difficulties-14-ways-to-maintain-command-of-a-virtual-room/",
    rating: 2,
  },
  {
    competency: "Digital Problem Solving",
    level: "attitudes",
    title: "Four Ways to Keep Teams Calm and Focused During a Crisis",
    description: "Discusses methods to maintain team composure and focus during crises, highlighting the role of leadership in fostering a calm and methodical problem-solving environment.",
    URL: "https://knowledge.wharton.upenn.edu/article/steady-troops-four-ways-keep-teams-calm-focused-crisis/",
    rating: 3,
  },
  {
    competency: "Digital Problem Solving",
    level: "attitudes",
    title: "7 Tips to Help Your Team with Problem-Solving",
    description: "Offers guidance on encouraging methodical problem-solving within teams, including promoting ownership and collaborative approaches to challenges.",
    URL: "https://www.optimistperformance.com/captains-blog/news/7-tips-to-help-your-team-with-problem-solving-by-optimist-performance/",
    rating: 4,
  },
  {
    competency: "Digital Problem Solving",
    level: "attitudes",
    title: "How to Promote Effective Problem Solving Strategies in Your Team",
    description: "Explores strategies to enhance problem-solving skills within teams, emphasising the importance of diverse perspectives and structured approaches to finding solutions.",
    URL: "https://herrmann.com.au/blog/2023/08/how-to-promote-effective-problem-solving-strategies/",
    rating: 5,
  },

  {
    competency: "Digital Creativity and Innovation",
    level: "knowledge",
    title: "Top 10 Easy-to-Use Creative Work Tools to Be More Productive",
    description: "Highlights user-friendly creative tools designed to boost productivity, detailing their features and applications.",
    URL: "https://www.domestika.org/en/blog/11326-top-10-easy-to-use-creative-work-tools-to-be-more-productive",
    rating: 1,
  },
  {
    competency: "Digital Creativity and Innovation",
    level: "knowledge",
    title: "Digital Workflow Solutions: All You Need To Know!",
    description: "Explores how digital workflow solutions streamline processes, enhance efficiency, and foster innovation within organisations.",
    URL: "https://www.process.st/digital-workflow-solutions/",
    rating: 2,
  },
  {
    competency: "Digital Creativity and Innovation",
    level: "knowledge",
    title: "How to Implement Digital Workflows",
    description: "Provides a comprehensive guide on adopting digital workflows, including selecting appropriate tools and recognising opportunities for process innovation.",
    URL: "https://www.smartsheet.com/content/digital-workflow",
    rating: 3,
  },
  {
    competency: "Digital Creativity and Innovation",
    level: "knowledge",
    title: "Digital Workflows Explained",
    description: "Delves into the concept of digital workflows, discussing their benefits and how they can be leveraged to enhance organisational efficiency and innovation.",
    URL: "https://www.servicenow.com/workflow/learn/digital-workflows-and-automation.html",
    rating: 4,
  },
  {
    competency: "Digital Creativity and Innovation",
    level: "knowledge",
    title: "What is a Digital Workflow? How to Automate It?",
    description: "Examines the automation of digital workflows, offering insights into tools and strategies that drive innovation and improve operational efficiency.",
    URL: "https://thedigitalprojectmanager.com/projects/pm-methodology/digital-workflows/",
    rating: 5,
  },
  {
    competency: "Digital Creativity and Innovation",
    level: "skills",
    title: "7 Idea Generation Methods for Out-of-the-Box Thinking",
    description: "Explores various techniques to stimulate creative thinking within teams, including mind mapping and brainstorming, to foster innovation.",
    URL: "https://www.notion.so/blog/idea-generation",
    rating: 1,
  },
  {
    competency: "Digital Creativity and Innovation",
    level: "skills",
    title: "10 Strategies of Encouraging Innovation in the Workplace",
    description: "Provides practical approaches to cultivate an innovative culture, such as encouraging diverse perspectives and allocating time for creative projects.",
    URL: "https://changemanagementinsight.com/encouraging-innovation-in-the-workplace/",
    rating: 2,
  },
  {
    competency: "Digital Creativity and Innovation",
    level: "skills",
    title: "16 Smart Ways to Ensure Team Members Adopt and Use New Tech Tools",
    description: "Offers strategies to facilitate the adoption of new technologies within teams, emphasising the importance of clear communication and training.",
    URL: "https://www.forbes.com/sites/forbestechcouncil/2022/07/27/16-smart-ways-to-ensure-team-members-adopt-and-use-new-tech-tools/",
    rating: 3,
  },
  {
    competency: "Digital Creativity and Innovation",
    level: "skills",
    title: "Generating Ideas: A Process for Breakthrough Innovation",
    description: "Discusses structured processes for idea generation, highlighting the significance of diverse teams and solo brainstorming in fostering innovation.",
    URL: "https://knowledge.wharton.upenn.edu/article/generating-ideas-a-process-for-breakthrough-innovation/",
    rating: 4,
  },
  {
    competency: "Digital Creativity and Innovation",
    level: "skills",
    title: "Mastering Idea Generation: A Comprehensive Guide to 30 Techniques",
    description: "Provides an extensive overview of idea management tools and techniques to boost creativity and streamline the innovation process within organisations.",
    URL: "https://fliplet.com/blog/mastering-idea-generation/",
    rating: 5,
  },
  {
    competency: "Digital Creativity and Innovation",
    level: "attitudes",
    title: "Thinking of Innovation as an Everyday Habit",
    description: "Discusses integrating innovation into daily routines, emphasising the importance of creative thinking and experimentation in regular tasks.",
    URL: "https://workspace.google.com/blog/future-of-work/thinking-of-innovation-as-an-everyday-habit",
    rating: 1,
  },
  {
    competency: "Digital Creativity and Innovation",
    level: "attitudes",
    title: "How to Be Innovative: Unlocking Creativity in Everyday Tasks",
    description: "Provides strategies for fostering innovation in routine activities, encouraging a mindset that seeks improvement and creative solutions.",
    URL: "https://georgenagle.com/blog/how-to-be-innovative-unlocking-creativity-in-everyday-tasks",
    rating: 2,
  },
  {
    competency: "Digital Creativity and Innovation",
    level: "attitudes",
    title: "7 Tips on How to Create a Culture of Continual Experimentation and Learning",
    description: "Offers practical advice on establishing a culture that promotes ongoing experimentation and learning within teams.",
    URL: "https://www.scrum.org/resources/blog/7-tips-how-create-culture-continual-experimentation-and-learning-and-how-overcome",
    rating: 3,
  },
  {
    competency: "Digital Creativity and Innovation",
    level: "attitudes",
    title: "How to Create a Continuous Improvement Culture: Strategies and Examples",
    description: "Explores methods to embed continuous improvement into organisational culture, highlighting the role of leadership and employee engagement.",
    URL: "https://www.hypeinnovation.com/blog/how-to-create-continuous-improvement-culture-strategies-and-examples",
    rating: 4,
  },
  {
    competency: "Digital Creativity and Innovation",
    level: "attitudes",
    title: "The Importance of Creativity in the Workplace",
    description: "Examines the significance of fostering creativity at work and its impact on innovation and problem-solving.",
    URL: "https://hrdailyadvisor.blr.com/2024/09/13/the-importance-of-creativity-in-the-workplace/",
    rating: 5,
  },
];

console.log("resources-es.js executed, window.customResources set for French.");
